#!/usr/bin/env bash

set -e

mkdir Playground
mkdir Playground/Algorithms
mkdir Playground/Algorithms.UnitTests
cd Playground
dotnet new sln
cd Algorithms
dotnet new classlib
cd ../Algorithms.UnitTests
dotnet new xunit
dotnet add reference ../Algorithms
dotnet add package Microsoft.DotNet.Watcher.Tools
dotnet add package Microsoft.NET.Test.Sdk
dotnet add package coverlet.collector
dotnet add package xunit
dotnet add package xunit.runner.visualstudio
cd ..
dotnet sln add Algorithms Algorithms.UnitTests
cd ..

